version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Activity Log: The Activity Log microservice
  ###################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      al_queue_name: Activity_Log
      PYTHONUNBUFFERED: 1
 
  #######################################################
  # Bank accounts: The Bank accounts microservice
  #######################################################
  bank_accounts:
    build:
      context: ./
      dockerfile: bank_accounts.Dockerfile
    restart: always
    environment:
      dbURL: postgresql://default:a9NucShgs4vC@ep-bold-band-a1oubdjz-pooler.ap-southeast-1.aws.neon.tech/verceldb
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  #######################################################
  # error: The error microservice
  #######################################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      e_queue_name: Error
      PYTHONUNBUFFERED: 1
  
  #######################################################
  # notification: The notification microservice
  #######################################################
  notification:
    build:
      context: ./
      dockerfile: notification.Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      n_queue_name: Notification
      PYTHONUNBUFFERED: 1

  #######################################################
  # transaction_history: The transaction_history microservice
  #######################################################
  transaction_history:
    build:
      context: ./
      dockerfile: transaction_history.Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: postgresql://default:BznZuKX3W9LQ@ep-soft-heart-a1pdoa7y-pooler.ap-southeast-1.aws.neon.tech/verceldb
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
  
  #######################################################
  # transfer_funds: The transfer_funds microservice
  #######################################################
  transfer_funds:
    build:
      context: ./
      dockerfile: transfer_funds.Dockerfile
    restart: always
    depends_on:
      - bank_accounts
      - user_accounts
      - transaction_history
      - activity_log
      - notification
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_accounts_URL : http://user_accounts:5000/user_accounts
      bank_accounts_URL : http://bank_accounts:5001/bank_accounts
      transaction_history_URL : http://transaction_history:5002/transaction_history
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  #######################################################
  # user_accounts: The user_accounts microservice
  #######################################################
  user_accounts:
    build:
      context: ./
      dockerfile: user_accounts.Dockerfile
    restart: always
    environment:
      dbURL: postgresql://default:vHFyts8wa4PK@ep-shiny-wave-a4w35od7-pooler.us-east-1.aws.neon.tech/verceldb
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  #######################################################
  # user_goal: The user_goal microservice
  #######################################################
  user_goal:
    build:
      context: ./
      dockerfile: user_goal.Dockerfile
    restart: always
    environment:
      dbURL: postgresql://default:vHFyts8wa4PK@ep-shiny-wave-a4w35od7-pooler.us-east-1.aws.neon.tech/verceldb
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit  # Corrected from 'hostnotification' to 'hostname'
    restart: always
    ports:
      - "5672:5672"
      # Uncomment the following line if you need to access the RabbitMQ management interface from your host machine
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq 
